### ISSUE TITLE
UML Diagrams/ SQL script

### ISSUE THREAD

**Issue by miguel-merlin** [stevensblueprint/blueprint_admin_backend#18]
## Description
Create a UML diagram with relationships. Then, update the `init.sql` script inside the `initdb` directory to reflect the newly created UML diagram. 

## Definition of Done
Test changes in the Docker container. If you have run the server before, you must delete the `postgres_data` directory generated by Docker when initializing the container. To trigger the script and initialize the db run `docker-compose up -d`.

Send screenshots verifying correct tables and relationships were made to the db.

**Comment by IvanFarfan08** [comment]
#19

**Comment by miguel-merlin** [comment]
Closed by #19
